# When issue is created with title "Deploy" and anybody
# comment "/deploy" in comment this workflow is triggered.
# This workflow publish the package in @next tag.

name: Process master branch for @next tag

on:
  issue_comment:
    types: [created]

jobs:
  prepare-master:
    if: (${{ github.event.issue.title == 'Deploy' }} && ${{ github.event.comment.body == '/deploy' && github.event.issue.state == 'open' }} && ${{ !github.event.issue.pull_request }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name bhoos-devops
          git config user.email devops@bhoos.com
          echo -e "github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
	  scope: '@bhoos'
	  
      - name: Install Dependencies and publish packages
        run: |
          yarn
          version=$(node -p "require('./package.json').version")
          echo "RELEASE_VERSION=v${version}" >> $GITHUB_ENV
          echo "ISSUE_NUMBER=${{github.event.issue.number}}" >> $GITHUB_ENV
          yarn build
          yarn publish --tag next
          git tag -a v${version} -m "v${version}"
          git push && git push --tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          
      - name: Create Release for moving to production
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }} (#${{ env.ISSUE_NUMBER }})
          commit: master
          body: ${{steps.github_release.outputs.changelog}}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
